### ISSUE TITLE
Typo in repo title

### ISSUE THREAD

**Issue by raphael-s** [p-svacha/arcticwebsite#21]
`arcticwebsite` -> `articwebsite`

:trollface:

**Comment by p-svacha** [comment]
Dear Raphael,
Thank you for your interest in this project. We will look into this and consider making your requested change. Unfortunately, I can not give you an estimated time of arrival nor can I promise that we will implement this change.

Have a nice day

**Comment by Chiirali** [comment]
I had a look into the mentioned issue. However, I found a more dramatic matter in issue #18 why isnt it called artic      gayming? 

-cheerz

**Comment by Shucki** [comment]
I do believe it should be called "arti aiming" and therefore I request that this repository shall be removed from the earth.

**Comment by ghost** [comment]
The "dramatic matter" which @Chiirali mentioned must be looked into asap. We are not aiming to offend any non-straight people so it should be necessary to include words of their foreign tongue in our repository.
